export const menus = [
    {
    id: 1,
    items: [
        {
            title: 'Login',
            type: 'page',
            menu_order: 1,
            parent_id: 0,
            url: '/information',
            is_button: false,
            fa_icon_code: 'fa-info-circle',
        },
        {
            title: 'Register',
            type: 'page',
            menu_order: 2,
            parent_id: 1,
            url: '/about-us',
            is_button: false,
            fa_icon_code: 'fa-users',
        },
        {
            title: 'My account',
            type: 'page',
            menu_order: 3,
            parent_id: 1,
            url: '/contact',
            is_button: false,
            fa_icon_code: 'fa-envelope',
        },
        {
            title: 'Orders',
            type: 'page',
            menu_order: 3,
            parent_id: 1,
            url: '/contact',
            is_button: false,
            fa_icon_code: 'fa-envelope',
        },
    ],
},

    {
        id: 2,
        items: [
            {
                title: 'Navigation',
                type: 'page',
                menu_order: 1,
                parent_id: 0,
                url: '/navigation',
                is_button: false,
                fa_icon_code: 'fa-compass',
            },
            {
                title: 'Home',
                type: 'page',
                menu_order: 2,
                parent_id: 2,
                url: '/',
                is_button: false,
                fa_icon_code: 'fa-home',
            },
            {
                title: 'Services',
                type: 'page',
                menu_order: 3,
                parent_id: 2,
                url: '/services',
                is_button: false,
                fa_icon_code: 'fa-cogs',
            },
        ],
    },
    {
        id: 3,
        items: [
            {
                title: 'Czarne rzęsy',
                type: 'page',
                menu_order: 1,
                parent_id: 0,
                url: '/navigation',
                is_button: false,
                fa_icon_code: 'fa-compass',
            },
            {
                title: 'NOWOŚĆ System UV',
                type: 'page',
                menu_order: 2,
                parent_id: 2,
                url: '/',
                is_button: false,
                fa_icon_code: 'fa-home',
            },
            {
                title: 'Preparaty do rzęs',
                type: 'page',
                menu_order: 3,
                parent_id: 2,
                url: '/services',
                is_button: false,
                fa_icon_code: 'fa-cogs',
            },
            {
                title: 'Rzęsy kolorowe',
                type: 'page',
                menu_order: 3,
                parent_id: 2,
                url: '/services',
                is_button: false,
                fa_icon_code: 'fa-cogs',
            },
            {
                title: 'end end',
                type: 'page',
                menu_order: 3,
                parent_id: 2,
                url: '/services',
                is_button: false,
                fa_icon_code: 'fa-cogs',
            },
        ],
    },
];
